default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: root
  password: password

development:
  <<: *default
  database: part_time_development

test:
  <<: *default
  database: part_time_test
